import type { Category, Product, Testimonial, Zone } from "./types";

export const FALLBACK_CATEGORIES: Category[] = [
  { id: "cubetas", name: "Cubetas", icon: "●", desc: "Tamaños #8 y #10, colores surtidos" },
  { id: "batidores", name: "Batidores", icon: "✽", desc: "Para cocina y repostería" },
  { id: "ganchos", name: "Ganchos", icon: "⏏", desc: "Infantil, súper eco y súper plus" },
  { id: "palanganas", name: "Palanganas", icon: "◡", desc: "Romana, caramelo, zebras, rombos" },
  { id: "cestos", name: "Cestos", icon: "▨", desc: "Para ropa y papeleros" },
  { id: "coladores", name: "Coladores", icon: "◉", desc: "Maxi, grado alimenticio" },
];

export const FALLBACK_PRODUCTS: Product[] = [
  {
    id: "cub-8",
    cat: "cubetas",
    name: "Cubeta #8",
    sku: "CB-008",
    price: 8.0,
    unit: "Paquete con 50 piezas",
    stock: "en bodega",
    badge: "Más vendido",
    specs: ["Paquete con 50 piezas", "Colores surtidos", "Tamaño chico"],
    colors: ["Surtido"],
    photo: "/products/cubeta-8.jpeg",
  },
  {
    id: "cub-10",
    cat: "cubetas",
    name: "Cubeta #10",
    sku: "CB-010",
    price: 11.5,
    unit: "Paquete con 50 piezas",
    stock: "en bodega",
    specs: ["Paquete con 50 piezas", "Colores surtidos", "Tamaño mediano"],
    colors: ["Surtido"],
    photo: "/products/cubeta-10.jpeg",
  },
  {
    id: "bat-2",
    cat: "batidores",
    name: "Batidor #2",
    sku: "BT-002",
    price: 1.85,
    unit: "Paquete con 100 piezas",
    stock: "en bodega",
    specs: ["Paquete con 100 piezas", "Para cocina y repostería", "Colores surtidos"],
    colors: ["Surtido"],
    photo: "/products/batidor-2.jpeg",
  },
  {
    id: "gan-inf",
    cat: "ganchos",
    name: "Gancho INFANTIL",
    sku: "GN-INF",
    price: 13.0,
    unit: "Bulto con 40 paquetes",
    stock: "en bodega",
    specs: ["Bulto con 40 paquetes", "Colores surtidos", "Para ropa de niño"],
    colors: ["Surtido"],
    photo: "/products/gancho-infantil.png",
  },
  {
    id: "gan-eco",
    cat: "ganchos",
    name: "Gancho SÚPER (eco)",
    sku: "GN-ECO",
    price: 16.0,
    unit: "Bulto con 40 paquetes",
    stock: "en bodega",
    specs: ["Bulto con 40 paquetes", "Ligero, económico", "Colores surtidos"],
    colors: ["Surtido"],
    photo: "/products/gancho-eco.jpeg",
  },
  {
    id: "gan-plus",
    cat: "ganchos",
    name: "Gancho súper PLUS",
    sku: "GN-PLS",
    price: 18.75,
    unit: "Bulto con 40 paquetes",
    stock: "en bodega",
    badge: "Más resistente",
    specs: ["Bulto con 40 paquetes", "Plástico reforzado", "Para ropa de adulto"],
    colors: ["Surtido"],
    photo: "/products/gancho-plus.jpeg",
  },
  {
    id: "pal-rom",
    cat: "palanganas",
    name: "Palangana romana sandy",
    sku: "PL-ROM",
    price: 15.0,
    unit: "Paquete con 50 piezas",
    stock: "en bodega",
    specs: ["Paquete con 50 piezas", "Colores sandy surtidos"],
    colors: ["Surtido"],
    photo: "/products/palangana-romana.jpeg",
  },
  {
    id: "pal-car",
    cat: "palanganas",
    name: "Palangana caramelo",
    sku: "PL-CAR",
    price: 13.0,
    unit: "Tamaño grande",
    stock: "en bodega",
    specs: ["Tamaño grande", "Colores caramelo surtidos"],
    colors: ["Surtido"],
    photo: "/products/palangana-caramelo.jpeg",
  },
  {
    id: "pal-zeb",
    cat: "palanganas",
    name: "Palangana zebras",
    sku: "PL-ZEB",
    price: 14.5,
    unit: "Paquete con 50 piezas",
    stock: "en bodega",
    specs: ["Paquete con 50 piezas", "Diseño zebras, colores surtidos"],
    colors: ["Surtido"],
    photo: "/products/palangana-zebras.jpeg",
  },
  {
    id: "pal-rmb",
    cat: "palanganas",
    name: "Palangana rombos",
    sku: "PL-RMB",
    price: 17.5,
    unit: "Clarificada",
    stock: "en bodega",
    specs: ["Palangana rombos clarificada", "Plástico translúcido"],
    colors: ["Clarificado"],
    photo: "/products/palangana-rombos.jpeg",
  },
  {
    id: "ces-tit",
    cat: "cestos",
    name: "Cesto para ropa TITÁN",
    sku: "CS-TIT",
    price: 73.0,
    unit: "Paquete con 30 piezas",
    stock: "en bodega",
    badge: "Tamaño grande",
    specs: ["Paquete con 30 piezas", "Para ropa", "Colores surtidos"],
    colors: ["Surtido"],
    photo: "/products/cesto-titan.jpeg",
  },
  {
    id: "ces-eco",
    cat: "cestos",
    name: "Cesto papelero ECO",
    sku: "CS-ECO",
    price: 10.0,
    unit: "Paquete con 50 piezas",
    stock: "en bodega",
    specs: ["Paquete con 50 piezas", "Papelero económico"],
    colors: ["Surtido"],
    photo: "/products/cesto-eco.jpeg",
  },
  {
    id: "ces-flr",
    cat: "cestos",
    name: "Cesto papelero FLOR",
    sku: "CS-FLR",
    price: 11.5,
    unit: "Paquete con 50 piezas",
    stock: "en bodega",
    specs: ["Paquete con 50 piezas", "Diseño flor, colores surtidos"],
    colors: ["Surtido"],
    photo: "/products/cesto-flor.jpeg",
  },
  {
    id: "col-max",
    cat: "coladores",
    name: "Colador Maxi",
    sku: "CO-MAX",
    price: 14.5,
    unit: "Paquete con 50 piezas",
    stock: "en bodega",
    specs: ["Paquete con 50 piezas", "Tamaño grande", "Colores surtidos"],
    colors: ["Surtido"],
    photo: "/products/colador-maxi.jpeg",
  },
];

export const FALLBACK_ZONES: Zone[] = [
  {
    name: "Zona Centro",
    speed: "Mismo día",
    cost: "Gratis desde $800",
    areas: ["Iztapalapa", "Iztacalco", "Venustiano Carranza", "Cuauhtémoc", "Benito Juárez"],
    color: "#1b7a3a",
  },
  {
    name: "Zona Norte",
    speed: "24 horas",
    cost: "Gratis desde $1,200",
    areas: ["Gustavo A. Madero", "Azcapotzalco", "Miguel Hidalgo"],
    color: "#c89b2a",
  },
  {
    name: "Zona Sur",
    speed: "24 horas",
    cost: "Gratis desde $1,200",
    areas: ["Coyoacán", "Tlalpan", "Xochimilco", "Tláhuac", "Milpa Alta"],
    color: "#c89b2a",
  },
  {
    name: "Zona Poniente",
    speed: "48 horas",
    cost: "Desde $180",
    areas: ["Álvaro Obregón", "Magdalena Contreras", "Cuajimalpa"],
    color: "#a8501f",
  },
  {
    name: "Estado de México",
    speed: "Coordinar",
    cost: "Bajo pedido",
    areas: ["Neza", "Ecatepec", "Chalco", "Valle de Chalco"],
    color: "#6a5438",
  },
];

export const FALLBACK_TESTIMONIALS: Testimonial[] = [
  {
    id: "testimonial-dona-rosa",
    name: "Doña Rosa",
    trade: "Mercado de Jamaica",
    text: "Me entregan las cubetas el mismo día que las pido. Tres años comprándole a don Mauricio y nunca falla.",
  },
  {
    id: "testimonial-el-guero",
    name: "Taller El Güero",
    trade: "Iztacalco",
    text: "Precios de mayoreo de verdad, sin mínimos absurdos. Siempre hay en bodega.",
  },
  {
    id: "testimonial-la-guera",
    name: "Tamales La Güera",
    trade: "Coyoacán",
    text: "Los ganchos plus aguantan lo que les pongas. Llevo años pidiéndole bultos.",
  },
];
